from .train_regression_rfr_xv import XVRandomForest
from .train_regression import TrainRegression
from .train_regression_lstm_xv import LSTMRegressionXV
from .train_regression_transformer_xv import TransformerRegressionXV